---
title: "Hands on R"
author: "Stefan"
date: "25 September 2016"
output:
  html_document:
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Don't Panic

This is where it all begins ...

```{r startup}
f = function() "R is cool!"
f()

lang = c("R", "Python", "Docker")
sprintf("%s is cool", lang)
```

## Leaflet ...

```{r leaflet}
# let's take a look at the quakes dataset ...
head(quakes)

# ... and put the first 20 rows to a leaflet map 
library(leaflet)

leaflet(data = quakes[1:20, ]) %>% addTiles() %>%
  addMarkers(popup = ~sprintf("<b>lat:</b> %s, <b>long:</b> %s, <b>mag:</b> %s", lat, long, mag))
```

## Everything is an object
You can use environments as (hashed) data structures.

```{r data structures}
e = new.env(parent = emptyenv())
e$name = "longhorse"
e$put = function() print(e$name)
e$put()
e$name = "stefan"
e$put()

library(magrittr)
values = sample(c("R", "Py"), 15, replace = T)
lookup = c(R = "Aaahrr", Py = "Python")
values
lookup[values] %>% unname()
```